# Generated by Django 2.0.3 on 2018-03-07 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('peso', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.PositiveSmallIntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='InformeActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0.0)),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica.Actividad')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica.Alumno')),
            ],
        ),
    ]
