# Generated by Django 2.0.3 on 2018-03-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeactividad',
            old_name='idActividad',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='informeactividad',
            old_name='idAlumno',
            new_name='alumno',
        ),
        migrations.AlterUniqueTogether(
            name='informeactividad',
            unique_together={('alumno', 'actividad')},
        ),
    ]
