# Generated by Django 2.0.3 on 2018-03-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_auto_20180307_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='practica.Actividad'),
        ),
        migrations.AlterField(
            model_name='informeactividad',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='practica.Alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='informeactividad',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='informeactividad',
            name='id',
        ),
    ]
